/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gt.edu.umg.sistema.estudiantes.vista;

import gt.edu.umg.sistema.estudiantes.controlador.FacturaController;
import gt.edu.umg.sistema.estudiantes.modelo.FACTURA;

import java.util.List;

/**
 *
 * @author Think
 */
public class FrmFactura extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmFactura.class.getName());

    FacturaController controller;

    /**
     * Creates new form FrmFactura
     */
    public FrmFactura() {
        initComponents();
        controller = new FacturaController();
        refrescarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroFactura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Facturación");

        jLabel1.setText("FACTURA");

        jLabel2.setText("No. Factura:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Cliente:");

        txtCliente.addActionListener(this::txtClienteActionPerformed);

        jLabel5.setText("Producto:");

        jLabel6.setText("Cantidad:");

        jLabel7.setText("Precio:");

        btnAgregar.setText("Agregar Producto");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        btnEliminar.setText("Eliminar Producto");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        lblTotal.setText("Total: Q 0.00");

        btnGuardar.setText("Guardar Factura");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(171, 171, 171)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(369, 369, 369)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(229, 229, 229)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotal)
                                .addGap(94, 94, 94))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    public void cargarDatosTabla() {
        List<FACTURA> listaFactura = controller.GetFacturas();

        String[] columnas = {"No. Factura", "Fecha", "Cliente", "Total" };

        // 3. Crear el modelo bloqueando la edición directa de celdas
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // 4. Recorrer la lista y agregar cada factura como una fila en la tabla
        for (FACTURA f : listaFactura) {
            Object[] fila = {
                    f.getNumeroFactura(),
                    f.getFecha(),
                    f.getCliente(),
                    f.getTotal()
            };
            modelo.addRow(fila);
        }

        tblProductos.setModel(modelo);
    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
        String producto = txtProducto.getText();
        int cantidad = Integer.parseInt(txtCantidad.getText());
        double precio = Double.parseDouble(txtPrecio.getText());

        double subtotal = cantidad * precio;

        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tblProductos.getModel();

        modelo.addRow(new Object[]{
            producto,
            cantidad,
            precio,
            subtotal
        });

        calcularTotal();

        txtProducto.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");

        txtProducto.requestFocus();

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Cantidad y precio deben ser números."
        );
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblProductos.getSelectedRow();

    if (filaSeleccionada == -1) {
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Seleccione un producto de la tabla."
    );
    return;
}

javax.swing.table.DefaultTableModel modelo =
        (javax.swing.table.DefaultTableModel) tblProductos.getModel();

modelo.removeRow(filaSeleccionada);

calcularTotal();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       try {
    // Validar que los datos principales estén completos
    if (txtNumeroFactura.getText().trim().isEmpty()
            || txtFecha.getText().trim().isEmpty()
            || txtCliente.getText().trim().isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Complete el número de factura, fecha y cliente."
        );
        return;
    }

    // Validar que exista al menos un producto
    if (tblProductos.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Debe agregar al menos un producto."
        );
        return;
    }

    // Validar y convertir la fecha (el usuario la escribe como dd/MM/yyyy)
    java.text.SimpleDateFormat formatoEntrada = new java.text.SimpleDateFormat("dd/MM/yyyy");
    formatoEntrada.setLenient(false);
    String fechaSql;
    try {
        java.util.Date fechaIngresada = formatoEntrada.parse(txtFecha.getText().trim());
        fechaSql = new java.sql.Date(fechaIngresada.getTime()).toString(); // queda en yyyy-MM-dd
    } catch (java.text.ParseException pe) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "La fecha debe tener el formato dd/mm/aaaa, por ejemplo 09/08/2026."
        );
        return;
    }

    // Crear la factura
    gt.edu.umg.sistema.estudiantes.modelo.FACTURA factura
            = new gt.edu.umg.sistema.estudiantes.modelo.FACTURA();

    factura.setNumeroFactura(
            Integer.parseInt(txtNumeroFactura.getText())
    );

    factura.setCliente(txtCliente.getText());
    factura.setFecha(fechaSql);

    // Recorrer la tabla
    for (int i = 0; i < tblProductos.getRowCount(); i++) {

        Object producto = tblProductos.getValueAt(i, 0);
        Object cantidad = tblProductos.getValueAt(i, 1);
        Object precio = tblProductos.getValueAt(i, 2);

        // Ignorar las filas vacías creadas por NetBeans
        if (producto != null && cantidad != null && precio != null) {

            gt.edu.umg.sistema.estudiantes.modelo.FacturaDetalle detalle
                    = new gt.edu.umg.sistema.estudiantes.modelo.FacturaDetalle(
                            producto.toString(),
                            Integer.parseInt(cantidad.toString()),
                            Double.parseDouble(precio.toString())
                    );

            factura.agregarDetalle(detalle);
        }
    }

    controller.Guardar(factura);

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Factura guardada correctamente.\n"
            + "Factura No. " + factura.getNumeroFactura() + "\n"
            + "Cliente: " + factura.getCliente() + "\n"
            + String.format("Total: Q %.2f", factura.getTotal())
    );

} catch (NumberFormatException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "El número de factura debe ser un número válido."
    );
} catch (RuntimeException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "No se pudo guardar la factura en la base de datos.\n"
            + "Verifique que la fecha tenga el formato aaaa-mm-dd y que el número de factura no esté repetido.\n"
            + "Detalle: " + e.getMessage()
    );
}
    }//GEN-LAST:event_btnGuardarActionPerformed
private void calcularTotal() {
 double total = 0;

    for (int i = 0; i < tblProductos.getRowCount(); i++) {

        Object valorSubtotal = tblProductos.getValueAt(i, 3);

        if (valorSubtotal != null) {
            total += Double.parseDouble(valorSubtotal.toString());
        }
    }

    lblTotal.setText(String.format("Total: Q %.2f", total));
}



    private void refrescarTabla() {
        try {
            cargarDatosTabla();
        } catch (Exception exception) {
            logger.severe("No se pudo cargar la lista de estudiantes:" + exception.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmFactura().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNumeroFactura;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
